#!/bin/bash -l
#PBS -N "76_S"
#PBS -j oe
#PBS -l walltime=4:00:00
#PBS -l select=1:ncpus=24:mem=144gb:mpiprocs=24


cd /home/zw18965/work/TMC151/TMD60/TPSSh-D3BJ

module load lib/openmpi
module load apps/orca
export orcadir="/sw/apps/orca/orca_4_2_0_linux_x86-64_openmpi314"
export RSH_COMMAND="/usr/bin/ssh -x"


#Setup scratch directory
cp "76_S.in" ${TMPDIR}
cp "76_S.xyz" ${TMPDIR}

# Run orca
cd ${TMPDIR}
export MKL_THREADING_LAYER=TBB

${orcadir}/orca "76_S.in" &> "76_S.out"

cp * /home/zw18965/work/TMC151/TMD60/TPSSh-D3BJ
cd /home/zw18965/work/TMC151/TMD60/TPSSh-D3BJ
